Repository Git-kkalnane/starbucks-backend-v2, pull requests merged in 2025-07, with the labels that each got.

#2 doc/ .github 추가
  .github/DISCUSSION_TEMPLATE/daily_work_report.yml
  .github/ISSUE_TEMPLATE/📌 -issue-template-.md
  .github/ISSUE_TEMPLATE/🛠️-bug- report-.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#5 [feat] DB에 Beverage 데이터 관계 맺는법과 mock Get API 추가
  sql/init_beverage_data.sql
  sql/init_dessert_data.sql
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/controller/ItemController.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/controller/item.http
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/domain/beverage/BeverageItem.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/domain/beverage/BeverageSupportedSize.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/domain/beverage/BeverageTemperatureOption.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/domain/dessert/DessertItem.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/domain/dessert/DessertItemService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/dto/BeverageItemDto.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/init/BeverageSupportedSizeDataInitializer.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/repository/BeverageItemRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/repository/BeverageSupportedSizeRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/repository/DessertItemRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/service/BeverageItemService.java
Labels: feature

#15 [refactor] order domain refactoring
  sql/init_item_option_data.sql
  sql/init_merchant.sql
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/domain/ItemOption.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/common/exception/OrderErrorCode.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/common/exception/OrderException.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/common/success/OrderSuccessCode.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/controller/OrderAPI.http
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/controller/OrderController.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/domain/Order.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/domain/OrderDailyCounter.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/domain/OrderDailyCounterId.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/domain/OrderItem.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/domain/OrderItemOption.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/request/OrderCreateRequest.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/request/OrderItemRequest.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/request/SelectedItemOptionRequest.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/request/StoreOrderStatusUpdateRequest.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/response/CustomerCurrentOrderResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/response/CustomerOrderDetailResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/response/CustomerOrderHistoryListResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/response/CustomerOrderHistoryResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/response/OrderCreateResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/response/StoreCurrentOrderResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/response/StoreHistoryOrderResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/response/StoreOrderDetailResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/response/StoreOrderHistoryListResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/repository/OrderDailyCounterRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/repository/OrderItemOptionRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/repository/OrderItemRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/repository/OrderRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/service/OrderService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/store/domain/Store.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/store/dto/StoreSimpleDto.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/store/repository/StoreRepository.java
Labels: refactor

#14 [refactor]: 모든 Entity @AllArgsConstructor 제거
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/member/domain/MemberRefreshToken.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/domain/beverage/BeverageItem.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/domain/dessert/DessertItem.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/member/domain/Member.java
Labels: refactor

#13 [refactor] PayCard 엔티티 구조 개선 및 리팩토링
  src/main/java/git_kkalnane/starbucksbackenv2/domain/member/event/MemberSignedUpEvent.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/member/event/MemberSignupEventListener.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/member/service/MemberService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/paycard/common/exception/PayCardErrorCode.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/paycard/common/exception/PayCardException.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/paycard/common/exception/PayTransactionErrorCode.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/paycard/common/exception/PayTransactionException.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/paycard/domain/PayCard.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/paycard/repository/PayCardRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/paycard/service/PayCardService.java
  src/test/java/git_kkalnane/starbucksbackenv2/StarbucksBackendV2ApplicationTests.java
  src/test/java/git_kkalnane/starbucksbackenv2/domain/paycard/service/PayCardServiceTest.java
Labels: feature

#23 [refactor] merchant domain refactoring
  sql/init_merchant.sql
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/merchant/controller/MerchantAPI.http
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/merchant/controller/MerchantAuthController.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/merchant/domain/MerchantRefreshToken.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/merchant/dto/MerchantLoginDto.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/merchant/dto/response/MerchantLoginResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/merchant/repository/MerchantRefreshTokenRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/merchant/service/MerchantAuthService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/merchant/common/exception/MerchantErrorCode.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/merchant/common/exception/MerchantException.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/merchant/common/success/MerchantSuccessCode.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/merchant/controller/MerchantController.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/merchant/controller/merchant.http
  src/main/java/git_kkalnane/starbucksbackenv2/domain/merchant/domain/Merchant.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/merchant/dto/request/SignUpRequest.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/merchant/dto/response/.gitkeep
  src/main/java/git_kkalnane/starbucksbackenv2/domain/merchant/repository/MerchantRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/merchant/service/MerchantService.java
  src/main/java/git_kkalnane/starbucksbackenv2/global/config/MerchantAuthInterceptor.java
  src/main/java/git_kkalnane/starbucksbackenv2/global/config/WebConfig.java
Labels: refactor

#24 [refactor] OrderItem Post & GET 추가
  sql/init_store_data.sql
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/domain/Order.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/domain/OrderItem.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/request/OrderItemRequest.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/response/CustomerOrderDetailResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/response/StoreCurrentOrderResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/response/StoreHistoryOrderResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/response/StoreOrderDetailResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/service/OrderItemService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/service/OrderService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/store/domain/Store.java
Labels: feature, refactor

#35 [chore] application.yml 파일 수정
  src/main/resources/application.yml
Labels: chore

#33 [feat] 카트아이템 삭제로직
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/common/success/CartSuccessCode.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/controller/CartController.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/repository/query/CartQueryRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/repository/query/CartQueryRepositoryImpl.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/service/CartService.java
Labels: feature

#40 [Refactor] 카트아이템 수량 수정 로직
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/common/exception/CartErrorCode.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/common/success/CartSuccessCode.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/controller/CartController.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/domain/CartItem.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/dto/request/CartItemDto.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/dto/request/ModifyCartItemDto.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/dto/response/CartItemResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/dto/response/ModifyCartItemResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/repository/CartItemOptionRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/repository/query/CartQueryRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/repository/query/CartQueryRepositoryImpl.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/service/CartService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/domain/ItemOption.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/domain/beverage/BeverageItem.java
Labels: refactor

#48 [Refactor] 카트아이템 수정 & 삭제 로직 검증
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/controller/CartController.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/domain/CartItem.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/domain/CartItemOption.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/dto/request/DeleteCartItemDto.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/dto/request/ModifyCartItemDto.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/service/CartOptionService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/service/CartService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/service/ValidAndCalculatorService.java
Labels: refactor

#64 [feature] 단일 디저트 조회 마이그레이션
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/controller/ItemController.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/controller/item.http
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/repository/DessertItemRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/service/DessertItemService.java
Labels: feature

#62 [feature] 단일 음료 조회 마이그레이션
  sql/fix_korean_collation.sql
  sql/init_dessert_data.sql
  sql/init_item_option_data.sql
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/controller/ItemController.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/controller/item.http
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/domain/beverage/BeverageItem.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/domain/dessert/DessertItem.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/dto/BeverageItemDto.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/dto/DessertItemDto.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/dto/ItemOptionDto.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/dto/response/DessertPaginationResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/dto/response/SingleBeverageResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/repository/BeverageItemQueryRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/repository/BeverageItemQueryRepositoryImpl.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/repository/DessertItemRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/repository/ItemOptionQueryRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/repository/ItemOptionQueryRepositoryImpl.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/repository/ItemOptionRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/service/BeverageItemService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/service/DessertItemService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/service/ItemOptionService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/service/OrderFactory.java
Labels: feature

#68 [Feat] 나만의 음료 조회하기
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/controller/FavoriteCartController.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/dto/request/favorite/CheckFavoriteCartItemDto.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/dto/request/favorite/CheckFavoriteCartItemOptionDto.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/dto/response/favorite/CheckFavoriteCartItemResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/repository/favorite/FavoriteCartItemRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/service/favorite/FavoriteCartItemCreateService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/service/favorite/FavoriteCartService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/service/favorite/FavoriteValidAndCalculatorService.java
Labels: feature

#72 [chore] 테스트용 도커 이미지 빌드 및 실행 파일 구현
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/git_kkalnane/starbucksbackenv2/global/config/MetricsConfig.java
  src/main/resources/application.yml
Labels: chore

#75 [fix]: 알림시에 발생한 getOrderItem NullPointerException 해결
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/domain/Order.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/service/OrderService.java
Labels: fix

#73 [feat] 주문번호 동시성 문제 해결
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/repository/OrderDailyCounterRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/service/OrderNumberGenerator.java
Labels: bug

#82 [feat] 음료, 디저트, 아이템 옵션 로직에 캐싱 추가
  build.gradle
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/service/BeverageItemService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/service/DessertItemService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/item/service/ItemOptionService.java
  src/main/java/git_kkalnane/starbucksbackenv2/global/config/CacheConfig.java
  src/main/java/git_kkalnane/starbucksbackenv2/global/config/CacheType.java
  src/main/resources/application.yml
Labels: feature

#85 [feat] 매장 단일, 목록 조회 로직에 캐싱 적용
  sql/init_store_data.sql
  src/main/java/git_kkalnane/starbucksbackenv2/domain/store/controller/StoreController.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/store/service/StoreService.java
  src/main/java/git_kkalnane/starbucksbackenv2/global/config/CacheType.java
Labels: feature

#90 [chore] 배포를 위한 준비
  .github/workflows/deploy.yml
  Dockerfile
  Dockerfile-test
  Dockerrun.aws.json
  docker-compose-test.yml
  src/test/java/git_kkalnane/starbucksbackenv2/domain/cart/CartTest.java
Labels: chore

#93 [fix] Dockerrun.aws.json 오타 수정
  Dockerrun.aws.json
Labels: fix

#98 fix: 파일 수정
  .github/workflows/deploy.yml
  Dockerrun.aws.json
Labels: fix

#102 [feat] 비활성화 되어 있는 멤버 로직 활성화
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/common/jwt/JwtTokenProvider.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/common/jwt/utils/TokenParser.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/member/controller/MemberAuthController.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/member/domain/MemberRefreshToken.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/member/dto/MemberLoginDto.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/member/service/MemberAuthService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/merchant/controller/MerchantAuthController.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/merchant/domain/MerchantRefreshToken.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/merchant/dto/MerchantLoginDto.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/auth/merchant/service/MerchantAuthService.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/member/controller/MemberController.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/member/domain/Member.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/member/service/MemberService.java
Labels: feature

#96 [feat] 프런트와 연결하기 위해 부족한 작업 수행
  src/main/java/git_kkalnane/starbucksbackenv2/domain/member/domain/Member.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/controller/MerchantOrderAPI.http
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/domain/OrderItem.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/response/CustomerCurrentOrderResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/response/CustomerOrderDetailResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/dto/response/StoreOrderDetailResponse.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/repository/OrderItemOptionRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/repository/OrderRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/order/service/OrderService.java
  src/main/java/git_kkalnane/starbucksbackenv2/global/config/MerchantAuthInterceptor.java
  src/main/java/git_kkalnane/starbucksbackenv2/global/config/WebConfig.java
Labels: feature, refactor

#99 [Refactor] 테스트 실패율 고려, 삭제 부분 로직 수정
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/controller/CartController.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/repository/CartItemOptionRepository.java
  src/main/java/git_kkalnane/starbucksbackenv2/domain/cart/service/CartService.java
Labels: refactor
